### ISSUE TITLE
🐞 Info.plist should be updated for each release

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-events-ios#146]
Looking at the [Info.plist](https://github.com/mapbox/mapbox-events-ios/blob/2e6bbd9f3c898f33a49e20fb97eca86eeb6351e4/MapboxMobileEvents/Info.plist)

we see

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>FMWK</string>
	<key>CFBundleShortVersionString</key>
	<string>0.9.5</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
</dict>
</plist>
```

Ideally for a release the fields currently using variables would be replaced with the current info. This might be the difference between building from source, and the SDK's inclusion in gl-native the code is currently built as part of that project. 

Edit: it looks as though this plist isn't a part of any target - should it be?

Can we do anything here @alfwatt?

Bonus: can we include the git sha in the plist too?

**Comment by alfwatt** [comment]
Turning on `INFOPLIST_PREPROCESS` is easy enough.

There are two 'Info.plist' files in the project:

[MapboxMobileEvents/Info.plist](https://github.com/mapbox/mapbox-events-ios/blob/2e6bbd9f3c898f33a49e20fb97eca86eeb6351e4/MapboxMobileEvents/Info.plist) is the plist for the `MapboxMobileEvents` framework target: 
`INFOPLIST_FILE = MapboxMobileEvents/Info.plist`

[resources/Info.plist](https://github.com/mapbox/mapbox-events-ios/blob/2e6bbd9f3c898f33a49e20fb97eca86eeb6351e4/resources/Info.plist) is the plist for the `resources` bundle target (which needs to go): `INFOPLIST_FILE = resources/Info.plist`

Neither is included as a resources, because they are optionally pre-processed and included as part of the build system.

Both have their version number updated by `make tag-version` which calls through to `scripts/package.sh -t $(VERSION)`, we could add a git command there to record the sha for the tag, but currently the script doesn't work well because we can't push directly to master.

**Comment by alfwatt** [comment]
Add common `Versions.h` with versions and git hash etc.
