### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-events-ios#24]
It looks like the latest version published to [cocoapods is v0.2.10](https://cocoapods.org/pods/MapboxMobileEvents) but the version in the podspec is [v0.2.12](https://github.com/mapbox/mapbox-events-ios/blob/d0b6d5a43a765279a8a1e9c52b87225cf8e377ed/MapboxMobileEvents.podspec#L6)

/cc @boundsj @rclee

**Comment by boundsj** [comment]
@rclee can you revert https://github.com/mapbox/mapbox-events-ios/commit/cec86be859b24bc9fb4d856f594402f19c2af141 to make the podspec match the published version again? That revert can close this issue and we will publish a new version when ready. The next version will be `v0.2.12` because of https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.2.11

**Comment by rclee** [comment]
Revert complete. See [`77b70af`](https://github.com/mapbox/mapbox-events-ios/commit/77b70af53895ffaced02c1bae2e1b2edbb2fb7f1)

**Comment by bsudekum** [comment]
Sorry to harp on this, but it looks like there is a tag ([v0.2.11](https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.2.11)) that is not published to cocoapods. This means users using Carthage and pods will each get a different version in mapbox-navigation-ios since carthage relies on tags.

**Comment by rclee** [comment]
I'll have to defer to @boundsj, this tag was created a bit before my time.

**Comment by boundsj** [comment]
Thanks for calling this out @bsudekum. 

I'm going to close again since [v0.2.11](https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.2.11) was tagged only to make [private a testing dependency installed via Carthage](https://github.com/mapbox/mapbox-events-ios/commit/b2665fb94581009b1395e515a340857d3e6c49b5) that was leaked downstream when Carthage was used for projects depending on this library.

In the future however, we will make sure to sync up all tags with pods releases as a general rule.
